mqtt:
  host: mqtt

detectors:
  coral:
    type: edgetpu
    device: pci:0
    model:
      path: /edgetpu_model.tflite

detect:
  width: 640
  height: 480
  fps: 5
  stationary:
    interval: 50
    threshold: 50

logger:
  logs:
    frigate.record: debug
    frigate.ptz.autotrack: debug
    frigate.ptz.onvif: debug

ffmpeg:
  #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  #hwaccel_args: preset-intel-qsv-h264
  #hwaccel_args: -c:v h264_qsv
  hwaccel_args: preset-vaapi

cameras:

  IP_CAM_DRIVEWAY_1:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.10:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.10:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    onvif:
      host: 10.13.0.10
      port: 80
      user: admin
      password: xe6t8w6LEtaKJKw
      autotracking:
        enabled: false
        calibrate_on_startup: false
        zooming: disabled
        track:
        - person
        - car
        required_zones: [zone_0]
        movement_weights: 0.2, 1.0, 6.642420291900635, 53783446.11234844, -25900335.400344003
    zones:
      zone_0:
        coordinates: 0,1080,1920,1080,1920,0,0,0

  IP_CAM_DRIVEWAY_2:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.5:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.5:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    objects:
      filters:
        car:
          mask:
          - 511,368,907,391,1485,417,1792,630,1538,1080,0,1080,0,378,98,293,129,282
          - 1836,244,1830,324,1723,286,1662,257,1676,168
          - 1268,100,1427,198,1157,166,1038,70

  IP_CAM_DRIVEWAY_3:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.6:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.6:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    objects:
      filters:
        car:
          mask:
          - 1373,748,1709,643,1641,354,1408,230,1151,208,1095,204,921,272,538,266,291,287,246,692
          - 1293,161,1385,217,1545,238,1497,143,1432,121,1286,102
          - 1812,314,1920,355,1920,264,1818,235

  IP_CAM_NORTHWEST:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.7:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.7:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    objects:
      filters:
        car:
          mask:
          - 838,130,824,196,586,195,634,144

  IP_CAM_GARAGE:
    ffmpeg:
      inputs:
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.3:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.3:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect

  DOORBELL:
    ffmpeg:
      inputs:
      - path:
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.8:554/cam/realmonitor?channel=1&subtype=0
        roles:
         - record       
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.8:554/cam/realmonitor?channel=1&subtype=1
        roles:
         - detect
    objects:
      filters:
        car:
          mask:
          - 1246,776,1387,857,1920,967,1920,817,1688,792,1741,747,1446,726
          - 1305,620,1449,647,1371,688,1233,678
objects:
  track:
  - person
  - car

record:
  enabled: true
  events:
    pre_capture: 30
    post_capture: 60
    objects:
    - person
    - car
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: false
  timestamp: false
  retain:
    default: 30

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: false

timestamp_style:
  format: '%Y/%m/%d %H:%M:%S'
