version: "3.9"

services:
#  homeassistant:
#    container_name: homeassistant
#    image: "ghcr.io/home-assistant/home-assistant:stable"
#    volumes:
#      - /media/nvr/homeassistant:/config
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    restart: unless-stopped
#    privileged: true
#    ports:
#      - "8123:8123"
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    depends_on:
      mqtt:
        condition: service_started
    devices:
#     - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#     - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/nvr/frigate/config.yml:/config/config.yml:ro
      - /media/nvr/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "${FRIGATE_RTSP_PASSWORD}"
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - "1883:1883"
