mqtt:
  host: mqtt

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

detect:
  width: 720
  height: 480  

ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  hwaccel_args: -c:v h264_qsv
cameras:
  IP_CAM_DRIVEWAY_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.4:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.4:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

      
  IP_CAM_DRIVEWAY_2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.5:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.5:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      
  IP_CAM_DRIVEWAY_3:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.6:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.6:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect


  IP_CAM_NORTHWEST:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.7:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.7:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect


  IP_CAM_GARAGE:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.3:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.3:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect


  DOORBELL:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.13.0.8
          roles:
            - detect

objects:
  track:
    - person
    
record:
  enabled: True
  events:
    pre_capture: 10
    post_capture: 20
    objects:
      - person
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: True
  bounding_box: True
  timestamp: True
  retain:
    default: 30

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False

timestamp_style:
  format: "%Y/%m/%d %H:%M:%S"
